### ISSUE TITLE
environment yml indentation

### ISSUE THREAD

**Issue by samburgers** [ngduc/node-rem#26]
Build steps currently fail early do to incorrect indentation of `environment:`

`docker-compose.dev.yml`
`docker-compose.prod.yml`

```
version: "2"
services:
  boilerplate-api:
    command: yarn dev -- -L
  environment:
    - NODE_ENV=development
```
should be

```
version: "2"
services:
  boilerplate-api:
    command: yarn dev -- -L
    environment:
      - NODE_ENV=development
```
